version: "3.8"

services:

  traefik:
    image: traefik:latest
    ports:
      - '80:80'
      - '8080:8080'
    command:
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--log.filePath=/var/log/traefik.log"
      - "--entrypoints.web.address=:80"
      - "--providers.docker"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      proxy:
        ipv4_address: 192.12.0.33

  wireguard:
    image: linuxserver/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - 'PUID=1001'
      - 'PGID=1001'
      - 'TZ=Europe/Moscow'
      - 'SERVERURL=auto'
      - 'SERVERPORT=51820'
      - 'PEERS=6'
      - 'PEERDNS=172.24.0.3'
      - 'INTERNAL_SUBNET=10.13.13.0'
    volumes:
      - '/etc/wireguard/config:/config'
      - '/lib/modules:/lib/modules'
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wireguard:
          ipv4_address: 172.24.0.2

  unbound:
    image: mvance/unbound:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - '/etc/unbound/:/opt/unbound/etc/unbound/'
    networks:
      wireguard:
          ipv4_address: 172.24.0.7

  doh-cloudflare:
    image: crazymax/cloudflared:latest
    restart: unless-stopped
    command: proxy-dns
    environment:
      - 'TUNNEL_DNS_PORT=53'
      - 'TUNNEL_DNS_ADDRESS=0.0.0.0'
      - 'TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://9.9.9.9/dns-query,https://149.112.112.9/dns-query'
    networks:
      wireguard:
          ipv4_address: 172.24.0.9

  pihole:
    image: pihole/pihole:latest
    expose:
      - 8080
    restart: unless-stopped
    environment:
      - 'WEBPASSWORD=test123'
      - 'DNS1=172.24.0.7'
      - 'DNS2=no'
      - 'DNSMASQ_LISTENING=all'
    # Volumes store your data between container upgrades
    volumes:
       - '/etc/pihole:/etc/pihole/'
       - '/etc/wireguard/dnsmasq.d:/etc/dnsmasq.d/'
       - '/etc/pihole/run/:/run/'
    dns:
      - 172.24.0.7
    cap_add:
      - NET_ADMIN
    networks:
      wireguard:
          ipv4_address: 172.24.0.3
      proxy:
          ipv4_address: 192.12.0.3
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.rule=PathPrefix(`/admin/`)"
      - "traefik.http.middlewares.sauth.basicauth.users=<username>:<passwrdhash>"
      - "traefik.http.middlewares.sauth.basicauth.removeheader=true"
      - "traefik.http.routers.pihole.middlewares=sauth"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

  ipsec:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    privileged: true
    environment:
      - 'VPN_DNS_SRV1=172.24.0.3'
      - 'VPN_DNS_SRV2=172.24.0.3'
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - '/etc/ipsec:/etc/ipsec.d'
      - '/lib/modules:/lib/modules:ro'
    networks:
      wireguard:
          ipv4_address: 172.24.0.5

  wgexporter:
    image: mindflavor/prometheus-wireguard-exporter:latest
    restart: unless-stopped
    command: -a true -v true
    environment:
      - 'PROMETHEUS_WIREGUARD_EXPORTER_PREPEND_SUDO_ENABLED=true'
    cap_add:
      - NET_ADMIN
    volumes:
      - '/etc/wireguard/config:/config'
      - '/lib/modules:/lib/modules'
    network_mode: service:wireguard

  nexporter:
    image: prom/node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    networks:
      wireguard:
          ipv4_address: 172.24.0.8

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      wireguard:
          ipv4_address: 172.24.0.10

  prometheus:
    hostname: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - '/etc/prometheus/:/etc/prometheus/'
    command:
      - '--web.external-url=http://$$(hostname):9090/prometheus/'
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      wireguard:
          ipv4_address: 172.24.0.6
      proxy:
          ipv4_address: 192.12.0.12
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus/`)"
      - "traefik.http.routers.prometheus.middlewares=sauth"

  grafana:
    hostname: grafana
    image: grafana/grafana:latest
    #environment:
    #  GF_SMTP_ENABLED: "true"
    #  GF_SMTP_HOST: "mailgateway:25"
    #  GF_SMTP_FROM_ADDRESS: "alert@myhost.com"
    expose:
      - 3000
    volumes:
      - '/etc/grafana/:/etc/grafana/'
    networks:
      wireguard:
          ipv4_address: 172.24.0.4
      proxy:
          ipv4_address: 192.12.0.5
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana/`)"
      - "traefik.http.routers.grafana.middlewares=sauth"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  wireguard:
    ipam:
        driver: default
        config:
            - subnet: 172.24.0.0/16
  proxy:
    ipam:
        driver: default
        config:
            - subnet: 192.12.0.0/16

